name: hotelmanagement
description: hotel management is an application for the management of a b and b or a hotel

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'



dependencies:
  intl: ^0.19.0
  cloud_firestore: ^4.12.0
  cupertino_icons: ^1.0.6
  firebase_app_check: ^0.2.1+2
  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  firebase_performance: ^0.9.3+2

  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.2
  flutter_markdown: ^0.6.18
  flutter_native_splash: ^2.3.4
  flutter_riverpod: ^2.4.4
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.8
  flutter_switch: ^0.3.2
  g_recaptcha_v3: ^0.0.5
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  page_transition: ^2.1.0
  syncfusion_flutter_datepicker: ^24.2.6
  uuid: ^3.0.5
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  image: assets/image.png
  color: "#009688"



